name: FE CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
      NEXT_PUBLIC_FRONTEND_BASE_URL: ${{ secrets.NEXT_PUBLIC_FRONTEND_BASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Verify node_modules integrity
        run: |
          echo "eslint-config-next version:"
          npm ls eslint-config-next || true
          echo "ESLint resolve test:"
          node -p "require.resolve('eslint-config-next/core-web-vitals')" || true


      - name: Create dummy .env.local
        run: |
          echo "NEXT_PUBLIC_API_URL=https://dummy.api" > .env.local

      - name: Run build
        run: npm run build

      - name: Run lint (optional)
        run: npm run lint
        continue-on-error: true

      - name: Run unit tests (optional)
        run: npm run test
        continue-on-error: true
